// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvki7bBsi6A1jLX5bQA1sPiOtnrM3_Y_c',
    appId: '1:861463450216:web:d9dfd7c8bcafe0990a21dd',
    messagingSenderId: '861463450216',
    projectId: 'retail-intel-d4a44',
    authDomain: 'retail-intel-d4a44.firebaseapp.com',
    storageBucket: 'retail-intel-d4a44.appspot.com',
    measurementId: 'G-TRH2BRMCG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQ7hmd6tznnqimm--bviMfZcyWcNU1_Q',
    appId: '1:861463450216:android:df1d63a5a74b43110a21dd',
    messagingSenderId: '861463450216',
    projectId: 'retail-intel-d4a44',
    storageBucket: 'retail-intel-d4a44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4MgWnx9MpzkZE_72a_1qt643EQUT2Ws',
    appId: '1:861463450216:ios:eb87ed4a0410c1f20a21dd',
    messagingSenderId: '861463450216',
    projectId: 'retail-intel-d4a44',
    storageBucket: 'retail-intel-d4a44.appspot.com',
    androidClientId: '861463450216-voa2j47j61mr46r37oocvoia78st90rq.apps.googleusercontent.com',
    iosClientId: '861463450216-grkgltl3fq171iprf2bv17ako2dfh92d.apps.googleusercontent.com',
    iosBundleId: 'com.example.retailIntelV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4MgWnx9MpzkZE_72a_1qt643EQUT2Ws',
    appId: '1:861463450216:ios:8242ef171b79897a0a21dd',
    messagingSenderId: '861463450216',
    projectId: 'retail-intel-d4a44',
    storageBucket: 'retail-intel-d4a44.appspot.com',
    androidClientId: '861463450216-voa2j47j61mr46r37oocvoia78st90rq.apps.googleusercontent.com',
    iosClientId: '861463450216-fmcov5prse8judtg10iefmg1utgbiqga.apps.googleusercontent.com',
    iosBundleId: 'com.example.retailIntelV2.RunnerTests',
  );
}
